### ISSUE TITLE
Flakey test failures

### ISSUE THREAD

**Issue by josephg** [nomad/cola#3]
Hi! I'm taking a look at cola. Your g-tree data structure looks to be several times faster than the b-tree I have in diamond types - which is super impressive! I'm considering using it.

I just ran the test suite for cola and got a failure:

```
$ cargo test
...
     Running tests/insertions.rs (target/debug/deps/insertions-53609808c6069dab)

running 5 tests
test conflicting_insertions_2 ... ok
test conflicting_insertions ... ok
test woot_figure_2 ... ok
test random_edits ... FAILED
test random_insertions ... ok

failures:

---- random_edits stdout ----
seed: 2497429969382240968
thread 'random_edits' panicked at /home/seph/3rdparty/cola/src/gtree.rs:1266:9:
assertion `left == right` failed
  left: 547
 right: 549
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    random_edits

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 16.21s
```

But I can't reproduce the failure. I assume each testing run is using rng with a random seed, and the seed is discarded when the test fails.

**Comment by noib3** [comment]
Hi Seph! This is fixed in b22f92816073626ac8e9e0cc4c12bde4f2a90473.

The panic was caused by an overly strict `debug_assertion`. Both the CI and I run the fuzzing tests in release mode, so I didn't catch it until now. Thanks a lot for reporting this.
